# Generated by Django 5.1.2 on 2024-10-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
