# Generated by Django 5.1.2 on 2024-10-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(max_length=10),
        ),
    ]
